config/routes.rb
What2eat::Application.routes.draw do

  resources :recipes

  root :to => redirect('/what2eat_homepages')

  get 'what2eat_homepages' => 'what2eat_homepages#index'

  get 'restaurants' => 'restaurants#index'
  post 'restaurants/' => 'restaurants#search'
  get 'foods' => 'foods#index'
  post 'foods' => 'foods#search'

end

app/models/food.rb
class Food < ActiveRecord::Base
  attr_accessible :energe, :name, :number
  
  validates :name, presence: true
  validates :number, presence: true, numericality: true
  validates :energe, presence: true, numericality: true
end

app/controllers/foods_controller.rb
# require 'open-uri'
# require 'Nokogiri'
require 'fatsecret'
class FoodsController < ApplicationController
  # GET /foods
  # GET /foods.json
  def index

    @foods = Food.all
    # p @foods
    # if @foods == null then
    #   p 'sdfsdfa'
    # end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @foods }
    end
  end

  def search
    FatSecret.init('1bc2cc311bb24d56a24322272e790419', '42c47bc7053247e2a43adfb8db57e6fc')
    @cal = params[:recipe]['ingre']
    # if @cal == nil
    #   flash[:notice] = "#{@cal}: calories cannot be null"
    #   redirect_to foods_path
    # end
    if @cal.to_i <= 0
      flash[:warning] = "Invalid input #{@cal}. Please input value > 0"
      redirect_to foods_path
    end
    @recommend_recipe = Recipe.where(['rcalorie < ?', @cal]).limit(10).order('rcalorie DESC')
    @array = []
    @recommend_recipe.each do |ele|
      @array.push(FatSecret.recipe(ele.rid))


    # session[:return_to] ||= request.referer

    end

    # @ingredient = params[:recipe]['ingre']
    # FatSecret.init('1bc2cc311bb24d56a24322272e790419', '42c47bc7053247e2a43adfb8db57e6fc')
    # @results = FatSecret.recipe(84411)
    # @description = @results['recipe']['directions']
    # @categories = @results['recipe']["recipe_categories"]["recipe_category"] #this is an array of hash
    # @str_cate = ''
    # @categories.each do |name|
    #   @str_cate << name["recipe_category_name"]
    #   @str_cate << ', '
    # end
    # @recipe_name = @results['recipe']["recipe_name"]
    # @recipe_id = @results['recipe']["recipe_id"]
    # @recipe_calories = @results['recipe']["serving_sizes"]["serving"]["calories"]
    # @recipe_rating = @results['recipe']['rating']
    # # @results = FatSecret.search_recipes(@ingredient, 50)
    # # @detail = @results['recipes']['recipe']
  end

  # # GET /foods/1
  # # GET /foods/1.json
  # def show
  #   @food = Food.find(params[:id])

  #   respond_to do |format|
  #     format.html # show.html.erb
  #     format.json { render json: @food }
  #   end
  # end

  # # GET /foods/new
  # # GET /foods/new.json
  # def new
  #   @food = Food.new

  #   respond_to do |format|
  #     format.html # new.html.erb
  #     format.json { render json: @food }
  #   end
  # end

  # # GET /foods/1/edit
  # def edit
  #   @food = Food.find(params[:id])
  # end

  # # POST /foods
  # # POST /foods.json
  # def create
  #   @food = Food.new(params[:food])

  #   respond_to do |format|
  #     if @food.save
  #       format.html { redirect_to @food, notice: 'Food was successfully created.' }
  #       format.json { render json: @food, status: :created, location: @food }
  #     else
  #       format.html { render action: "new" }
  #       format.json { render json: @food.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # PUT /foods/1
  # # PUT /foods/1.json
  # def update
  #   @food = Food.find(params[:id])

  #   respond_to do |format|
  #     if @food.update_attributes(params[:food])
  #       format.html { redirect_to @food, notice: 'Food was successfully updated.' }
  #       format.json { head :no_content }
  #     else
  #       format.html { render action: "edit" }
  #       format.json { render json: @food.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # DELETE /foods/1
  # # DELETE /foods/1.json
  # def destroy
  #   @food = Food.find(params[:id])
  #   @food.destroy

  #   respond_to do |format|
  #     format.html { redirect_to foods_url }
  #     format.json { head :no_content }
  #   end
  # end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/_form.html.erb
<%= form_for(@food) do |f| %>
  <% if @food.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
      <% @food.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :energe %><br />
    <%= f.text_field :energe %>
  </div>
  <div class="field">
    <%= f.label :number %><br />
    <%= f.number_field :number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/foods/edit.html.erb
<h1>Editing food</h1>

<%= render 'form' %>

<%= link_to 'Show', @food %> |
<%= link_to 'Back', foods_path %>

app/views/foods/index.html.haml
%h1 Search Food and Recipes


%table
  %thead

  %tbody
  - @foods.each do |food|
    %tr
      %td= food.name
      %td= food.energy

= form_tag foods_path, :method => :post do
  = label :recipe, :ingre, 'Calories Needed'
  = text_field :recipe, :ingre
  = submit_tag 'Search for Recipe', class: "btn btn-xs edituser"

  = link_to "Back", what2eat_homepages_path, :method => :get, class: "btn btn-xs edituser"

/ %table
/   %thead
/     %tr
/       %th = form_tag foods_path, :method => :post do
/             = label :recipe, :ingre, 'Calories Needed'
/             = text_field :recipe, :ingre
/             = submit_tag 'Search for Recipe'
/       %th = link_to "Back", what2eat_homepages_path, :method => :get, class: "btn btn-xs edituser"

%table
  %thead
    %tr
      %th Women
      %th Men

  %tbody
    %tr
      %td= image_tag('http://www.chartsgraphsdiagrams.com/HealthCharts/images/calorie-requirement-women.png')
      %td= image_tag('http://www.chartsgraphsdiagrams.com/HealthCharts/images/calorie-requirement-men.png')

app/views/foods/new.html.erb
<h1>New food</h1>

<%= render 'form' %>

<%= link_to 'Back', foods_path %>

app/views/foods/search.html.haml
%h1 Search results

%h2= @ingredient

/ %h2= @detail

/ %h3= @results['recipe']["serving_sizes"]["serving"]["calories"]
/ %h3= @results


/ %h3= @recipe_name
/ %h4= @recipe_id
/ %h4= @recipe_calories
/ %h4= @str_cate
/ %h4= @description

/ - @results['recipe']['directions'].each do |description|
/ 	%h3= 

/ %table
/ 	%thead
/ 		%tr
/ 			%th Name
/ 			%th Discription
/ 			%th Image
/ 			%th Id
/ 			%th More Information

/ 	%tbody
/ 	- @detail.each do |recipe|
/ 		%tr
/ 			%td= recipe['recipe_name']
/ 			%td= recipe['recipe_description']
/ 			%td= image_tag(recipe['recipe_image'])
/ 			%td= recipe['recipe_id']
/ 			%td= link_to "details", recipe['recipe_url']

/ %h3= @array[1]['recipe']["recipe_description"]
/ %h3= image_tag(@array[1]['recipe']["recipe_images"]["recipe_image"])
/ - n = 0
/ - for i in 1..10
/ 	%h3= @array[n]['recipe']["recipe_description"]
/ 	- if @array[n]['recipe']["recipe_images"] != nil
/ 		%h3= image_tag(@array[n]['recipe']["recipe_images"]["recipe_image"])
/ 	- n = n + 1

%table.table.table-striped
	%thead
		%tr
			%th Name
			%th Discription
			%th Rating
			%th KCalories/serving
			%th image

	%tbody
	- n = 0
	- @recommend_recipe.each do |recipe|
		- ele = @array[n]
		%tr
			%td= link_to recipe.rname, recipe_path(recipe)
			- if ele['recipe'] != nil
				%td= ele['recipe']["recipe_description"]
			- else
				%td No discription
			%td= recipe.rrating
			%td= recipe.rcalorie
			- if ele['recipe']["recipe_images"] != nil
				%td= image_tag(ele['recipe']["recipe_images"]["recipe_image"], :size => '153x110')
			- else
				%td= image_tag("http://www.changefood.org/wp-content/uploads/2013/09/feel-healthier-bodymind-fresh-food-better-than-canned_32-150x150.jpg", :size => '153x110')
		- n = n + 1

= link_to "Back", foods_path, :method => :get, class: "btn btn-xs edituser"

app/views/foods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @food.name %>
</p>

<p>
  <b>Energe:</b>
  <%= @food.energe %>
</p>

<p>
  <b>Number:</b>
  <%= @food.number %>
</p>


<%= link_to 'Edit', edit_food_path(@food) %> |
<%= link_to 'Back', foods_path %>