config/routes.rb
What2eat::Application.routes.draw do

  resources :recipes

  root :to => redirect('/what2eat_homepages')

  get 'what2eat_homepages' => 'what2eat_homepages#index'

  get 'restaurants' => 'restaurants#index'
  post 'restaurants/' => 'restaurants#search'
  get 'foods' => 'foods#index'
  post 'foods' => 'foods#search'

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  attr_accessible :number, :rname

  validates :rname, presence: true
  validates :number, presence: true, numericality: true
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  # rescue_from RestaurantsController::UNAVAILABLE_FOR_LOCATION, with: :unavailable_location
  # GET /restaurants
  # GET /restaurants.json
  # def unavailable_location
  #     render plain: "404 Not Found", status: 404
  # end


  def index
    @restaurants = Restaurant.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @restaurants }
    end
  end

  def search
    @address = params[:place]['address']

    # set default address
    if @address.length == 0
      flash[:warning] = "Invalid input. Please type in an address"
      redirect_to restaurants_path
    else
      parameters = {  limit: 10,
                      term: 'restaurants, food',
                      sort: 2,
                      radius_filter: 1600
                   }

      locale = { cc: 'US' }
      begin
        @results = Yelp.client.search(@address, parameters, locale)
      rescue
        flash[:warning] = "Invalid address. Please type in an valid address" 
        redirect_to restaurants_path
      end
    end
  end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_form.html.erb
<%= form_for(@restaurant) do |f| %>
  <% if @restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
      <% @restaurant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :rname %><br />
    <%= f.text_field :rname %>
  </div>
  <div class="field">
    <%= f.label :number %><br />
    <%= f.number_field :number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing restaurant</h1>

<%= render 'form' %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.haml
%h1 Search Restaurants

= form_tag restaurants_path, :method => :post do
  = label :place, :address, 'Address'
  = text_field :place, :address
  = submit_tag 'Search',  class: "btn btn-xs edituser"

  = link_to "Back", what2eat_homepages_path, :method => :get, class: "btn btn-xs edituser"
  

app/views/restaurants/new.html.erb
<h1>New restaurant</h1>

<%= render 'form' %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/search.html.haml
%h1 Search results

%h2= @address

/ %h3= @results

%table.table.table-striped
	%thead
		%tr
			%th
			%th Name
			%th Rating
			%th Address
			/ %th Phone
			%th More Information

	%tbody
	- @results.businesses.each do |restaurant|
		%tr
			%td= image_tag(restaurant.image_url)
			%td= restaurant.name
			%td= restaurant.rating
			%td= restaurant.location.display_address
			/ %td= restaurant.display_phone
			%td= link_to "details", restaurant.url, :target => "_blank" 


= link_to "Back", restaurants_path, :method => :get, class: "btn btn-xs edituser"

app/views/restaurants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Rname:</b>
  <%= @restaurant.rname %>
</p>

<p>
  <b>Number:</b>
  <%= @restaurant.number %>
</p>


<%= link_to 'Edit', edit_restaurant_path(@restaurant) %> |
<%= link_to 'Back', restaurants_path %>